
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'API_ANNOTATION API_SUMMARY NAME SCOPE_BEGIN SCOPE_ENDstart : NAME SCOPE_BEGIN service SCOPE_ENDservice : service api\n\t            | apiapi : NAME annotationsannotations : API_ANNOTATION api_summary\n\t               | api_summaryapi_summary : API_SUMMARY\n\t                |'
    
_lr_action_items = {'NAME':([0,3,4,5,6,7,8,9,10,12,13,],[2,4,-8,4,-3,-4,-8,-6,-7,-2,-5,]),'$end':([1,11,],[0,-1,]),'SCOPE_BEGIN':([2,],[3,]),'API_ANNOTATION':([4,],[8,]),'API_SUMMARY':([4,8,],[10,10,]),'SCOPE_END':([4,5,6,7,8,9,10,12,13,],[-8,11,-3,-4,-8,-6,-7,-2,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'service':([3,],[5,]),'api':([3,5,],[6,12,]),'annotations':([4,],[7,]),'api_summary':([4,8,],[9,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> NAME SCOPE_BEGIN service SCOPE_END','start',4,'p_start','api_yacc.py',5),
  ('service -> service api','service',2,'p_service','api_yacc.py',13),
  ('service -> api','service',1,'p_service','api_yacc.py',14),
  ('api -> NAME annotations','api',2,'p_api','api_yacc.py',23),
  ('annotations -> API_ANNOTATION api_summary','annotations',2,'p_annotations','api_yacc.py',29),
  ('annotations -> api_summary','annotations',1,'p_annotations','api_yacc.py',30),
  ('api_summary -> API_SUMMARY','api_summary',1,'p_api_summary','api_yacc.py',40),
  ('api_summary -> <empty>','api_summary',0,'p_api_summary','api_yacc.py',41),
]
